import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ─── Prices ───────────────────────────────────────────────────────────────────
const DEFAULT_PRICES = {
  panelPerWatt: 55, batteryPerAh12V: 145, inverterPerWatt: 28,
  regulatorPerAmp: 450, installationPct: 15, cableAndMiscFixed: 25000,
  sonelgazTariff: 5.0,
};

export function computeDefaultCosts(type: string, results: any) {
  const panelsCost    = (results.systemCapacitykW || 0) * 1000 * DEFAULT_PRICES.panelPerWatt;
  const batteriesCost = (type === "off-grid" || type === "hybrid")
    ? (results.totalBatteries || 0) * 200 * DEFAULT_PRICES.batteryPerAh12V : 0;
  const inverterW     = type === "on-grid"
    ? (results.inverterCapacitykW || 0) * 1000 : (results.inverterCapacityW || 0);
  const inverterCost  = inverterW * DEFAULT_PRICES.inverterPerWatt;
  const regulatorCost = (results.mpptRatingA || 0) * DEFAULT_PRICES.regulatorPerAmp;
  const materialCost  = panelsCost + batteriesCost + inverterCost + regulatorCost + DEFAULT_PRICES.cableAndMiscFixed;
  const installCost   = materialCost * (DEFAULT_PRICES.installationPct / 100);
  const total         = materialCost + installCost;
  const annualKwh     = type === "on-grid" && results.dailyProductionkWh
    ? results.dailyProductionkWh * 365
    : (results.systemCapacitykW || 0) * 5 * 365 * 0.82;
  const annualSavings = annualKwh * DEFAULT_PRICES.sonelgazTariff;
  const paybackYears  = total / (annualSavings || 1);
  const savingsOver25 = annualSavings * 25 - total;
  return {
    costs: { panels: panelsCost, batteries: batteriesCost, inverter: inverterCost, regulator: regulatorCost, cableAndMisc: DEFAULT_PRICES.cableAndMiscFixed, installation: installCost, total },
    roi:   { annualSavings, paybackYears, savingsOver25 },
  };
}

// ─── Colors ───────────────────────────────────────────────────────────────────
const GREEN:  [number,number,number] = [34,  197,  94];
const BLACK:  [number,number,number] = [20,  20,   20];
const GRAY:   [number,number,number] = [100, 100, 100];
const LGRAY:  [number,number,number] = [240, 240, 240];
const WHITE:  [number,number,number] = [255, 255, 255];
const DGRAY:  [number,number,number] = [60,  60,  60];
const HEAD:   [number,number,number] = [45,  45,   45];

// ─── Month names ──────────────────────────────────────────────────────────────
const MONTH_NAMES = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

// ─── Translations (English-only) ──────────────────────────────────────────────
const T = {
  subtitle:        "Solar PV Sizing Report",
  secSpec:         "SYSTEM SPECIFICATIONS",
  secCost:         "FINANCIAL ANALYSIS",
  secROI:          "RETURN ON INVESTMENT",
  secMonthly:      "MONTHLY SOLAR RESOURCES",
  secSeason:       "SEASONAL ANALYSIS",
  secInstall:      "INSTALLATION RECOMMENDATIONS",
  secSpacing:      "PANEL SPACING & SHADING ANALYSIS",
  paramCol:        "Parameter",
  valueCol:        "Value",
  unitCol:         "Unit",
  costItem:        "Cost Item",
  amount:          "Amount (DZD)",
  share:           "Share (%)",
  totalInvest:     "TOTAL ESTIMATED INVESTMENT",
  annualSavings:   "Annual Energy Savings (est.)",
  payback:         "Simple Payback Period",
  netProfit:       "Net Profit over 25-year lifespan",
  roi25:           "25-year ROI",
  tariff:          "Sonelgaz tariff used",
  monthCol:        "Month",
  ghiCol:          "GHI (kWh/m²/d)",
  tempCol:         "Max Temp (°C)",
  yieldCol:        "1 kWp Yield (kWh)",
  shareCol:        "Annual Share (%)",
  classCol:        "Classification",
  annAvg:          "Annual Average / Total",
  season:          "Season",
  avgGhi:          "Avg GHI (kWh/m²/d)",
  annGhi:          "Annual GHI (kWh/m²)",
  avgTemp:         "Avg Max Temp (°C)",
  classif:         "Classification",
  tiltAnn:         "Optimal tilt angle (annual)",
  tiltWin:         "Optimal tilt — winter",
  tiltSum:         "Optimal tilt — summer",
  azimuth:         "Azimuth (orientation)",
  pr:              "Recommended PR (system)",
  yieldKwp:        "Expected 1 kWp annual yield",
  co2:             "CO₂ avoided per kWp",
  solar:           "Solar fraction potential",
  recValue:        "Recommended Value",
  notes:           "Notes",
  footer:          "LuminaSizer  ·  Solar PV Sizing Platform  ·  Results are indicative — consult a certified engineer before installation.",
  disclaimer:      "This report is computer-generated by LuminaSizer. Results are indicative.",
  panelLen:        "Panel Length (L)",
  tiltAngle:       "Tilt Angle (β)",
  latitude:        "Latitude",
  rowSpacing:      "Row Spacing (d)",
  dMin:            "Minimum Spacing (d_min)",
  winterElev:      "Winter Sun Elevation",
  summerElev:      "Summer Sun Elevation",
  winShadow:       "Winter Shadow Length",
  sumShadow:       "Summer Shadow Length",
  gcr:             "Ground Coverage Ratio (GCR)",
  shadedFrac:      "Shaded Fraction",
  annualLoss:      "Annual Loss (est.)",
  status:          "Status",
};

const SYSTEM_LABELS: Record<string, string> = {
  "on-grid":  "On-Grid Solar System",
  "off-grid": "Off-Grid Solar System",
  "hybrid":   "Hybrid Solar System",
  "pumping":  "Solar Pumping System",
};

function fmt(n: number) { return n.toLocaleString("en-US", { maximumFractionDigits: 0 }); }

// ─── Canvas chart helpers ──────────────────────────────────────────────────────
function makeBarImage(
  months: { label: string; value: number }[],
  w = 560, h = 200
): string {
  const canvas = document.createElement("canvas");
  canvas.width = w; canvas.height = h;
  const ctx = canvas.getContext("2d")!;

  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, w, h);

  const padL = 44, padR = 10, padT = 22, padB = 38;
  const chartW = w - padL - padR;
  const chartH = h - padT - padB;
  const maxVal = Math.max(...months.map(m => m.value)) * 1.1;
  const slotW  = chartW / 12;
  const barW   = slotW * 0.65;

  // Y-axis gridlines + labels
  const ticks = 4;
  for (let i = 0; i <= ticks; i++) {
    const val = (maxVal * i) / ticks;
    const yy  = padT + chartH - (chartH * i) / ticks;
    ctx.strokeStyle = "#e5e7eb";
    ctx.lineWidth   = 0.8;
    ctx.beginPath(); ctx.moveTo(padL, yy); ctx.lineTo(w - padR, yy); ctx.stroke();
    ctx.fillStyle  = "#6b7280";
    ctx.font       = "11px sans-serif";
    ctx.textAlign  = "right";
    ctx.fillText(val.toFixed(1), padL - 4, yy + 4);
  }

  // Bars
  months.forEach((m, i) => {
    const pct  = m.value / maxVal;
    const barH = pct * chartH;
    const x    = padL + i * slotW + (slotW - barW) / 2;
    const y    = padT + chartH - barH;

    // gradient color
    const grad = ctx.createLinearGradient(x, y, x, y + barH);
    if (pct > 0.82) {
      grad.addColorStop(0, "#fbbf24"); grad.addColorStop(1, "#f59e0b");
    } else if (pct > 0.6) {
      grad.addColorStop(0, "#34d399"); grad.addColorStop(1, "#10b981");
    } else {
      grad.addColorStop(0, "#6ee7b7"); grad.addColorStop(1, "#34d399");
    }
    ctx.fillStyle = grad;
    ctx.beginPath();
    ctx.roundRect(x, y, barW, barH, 3);
    ctx.fill();

    // value label on top
    ctx.fillStyle  = "#374151";
    ctx.font       = "9px sans-serif";
    ctx.textAlign  = "center";
    ctx.fillText(m.value.toFixed(2), x + barW / 2, y - 4);

    // month label bottom
    ctx.fillStyle  = "#4b5563";
    ctx.font       = "10px sans-serif";
    ctx.fillText(m.label.slice(0, 3), x + barW / 2, h - padB + 14);
  });

  // Y-axis title
  ctx.save();
  ctx.translate(12, h / 2);
  ctx.rotate(-Math.PI / 2);
  ctx.fillStyle  = "#6b7280";
  ctx.font       = "11px sans-serif";
  ctx.textAlign  = "center";
  ctx.fillText("GHI (kWh/m²/d)", 0, 0);
  ctx.restore();

  return canvas.toDataURL("image/png");
}

function makePieImage(
  slices: { label: string; value: number; color: string }[],
  w = 540, h = 240
): string {
  const canvas = document.createElement("canvas");
  canvas.width = w; canvas.height = h;
  const ctx = canvas.getContext("2d")!;

  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, w, h);

  const cx = 130, cy = h / 2, r = 100;
  const total = slices.reduce((s, sl) => s + sl.value, 0);

  let angle = -Math.PI / 2;
  slices.forEach(sl => {
    const sweep = (sl.value / total) * 2 * Math.PI;
    ctx.beginPath();
    ctx.moveTo(cx, cy);
    ctx.arc(cx, cy, r, angle, angle + sweep);
    ctx.closePath();
    ctx.fillStyle = sl.color;
    ctx.fill();
    ctx.strokeStyle = "#ffffff";
    ctx.lineWidth = 2;
    ctx.stroke();
    angle += sweep;
  });

  // Legend
  const lx = 270, ly0 = 30;
  ctx.font = "bold 13px sans-serif";
  ctx.fillStyle = "#111827";
  ctx.textAlign = "left";
  ctx.fillText("Cost Breakdown", lx, ly0);

  slices.forEach((sl, i) => {
    const yy  = ly0 + 22 + i * 28;
    const pct = ((sl.value / total) * 100).toFixed(1);
    ctx.fillStyle = sl.color;
    ctx.beginPath();
    ctx.roundRect(lx, yy - 11, 14, 14, 3);
    ctx.fill();
    ctx.fillStyle  = "#1f2937";
    ctx.font       = "11px sans-serif";
    const lbl = sl.label.length > 28 ? sl.label.slice(0, 28) + "…" : sl.label;
    ctx.fillText(`${lbl}  —  ${pct}%`, lx + 20, yy);
  });

  return canvas.toDataURL("image/png");
}

const PIE_COLORS = ["#f59e0b","#10b981","#7c3aed","#f43f5e","#fb923c","#60a5fa"];

function classify(irr: number): string {
  if (irr >= 6.5) return "Excellent";
  if (irr >= 5.5) return "Very Good";
  if (irr >= 4.5) return "Good";
  return "Moderate";
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
function secHeader(doc: jsPDF, num: string, title: string, y: number): number {
  doc.setFillColor(...GREEN);
  doc.rect(14, y, 2, 8, "F");
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BLACK);
  doc.text(`${num}  ${title}`, 19, y + 6.5);
  doc.setDrawColor(...LGRAY);
  doc.setLineWidth(0.3);
  doc.line(14, y + 10, 196, y + 10);
  return y + 15;
}

function docHeader(doc: jsPDF, subtitle: string) {
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, 210, 4, "F");
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...GREEN);
  doc.text("LuminaSizer", 14, 14);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GRAY);
  doc.text(subtitle, 14, 20);
  doc.setDrawColor(...LGRAY);
  doc.setLineWidth(0.4);
  doc.line(14, 23, 196, 23);
}

function docFooter(doc: jsPDF, page: number, total: number, footerText: string) {
  const h = 297;
  doc.setDrawColor(...LGRAY);
  doc.setLineWidth(0.3);
  doc.line(14, h - 10, 196, h - 10);
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...GRAY);
  doc.text(footerText, 14, h - 6, { maxWidth: 160 });
  doc.text(`${page} / ${total}`, 196, h - 6, { align: "right" });
}

function metaBlock(doc: jsPDF, rows: [string, string][], y: number): number {
  const LW = 65;
  for (const [label, value] of rows) {
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...GRAY);
    doc.text(label, 14, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...BLACK);
    doc.text(value, 14 + LW, y);
    y += 5.5;
  }
  return y + 3;
}

// ─── PROJECT PDF ──────────────────────────────────────────────────────────────
export interface PdfOptions {
  projectName: string;
  systemType: string;
  location: { lat: number; lon: number; psh: number } | null;
  results: any;
  costs?: {
    panels: number; batteries: number; inverter: number;
    regulator: number; cableAndMisc: number; installation: number; total: number;
  };
  roi?: { annualSavings: number; paybackYears: number; savingsOver25: number };
  monthly?: { label: string; irr: number; temp: number }[];
  spacing?: {
    L: number; tilt: number; lat: number; d: number;
    dMin: number; gcr: number; solarElevWinter: number; solarElevSummer: number;
    shadowLengthWinter: number; shadowLengthSummer: number;
    shadedFraction: number; annualLoss: number;
  };
  lang?: "en" | "fr" | "ar";
}

export function generateProjectPdf(opts: PdfOptions) {
  const { projectName, systemType, location, results, costs, roi, monthly, spacing } = opts;
  const t       = T;
  const mon     = MONTH_NAMES;
  const sysName = SYSTEM_LABELS[systemType] ?? systemType;
  const PR      = 0.82;

  const doc     = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const addPage = () => { doc.addPage(); docHeader(doc, t.subtitle); };
  let y = 0;

  docHeader(doc, t.subtitle);
  y = 30;

  // ── Project title block ──
  doc.setFillColor(...LGRAY);
  doc.rect(14, y, 182, 24, "F");
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BLACK);
  doc.text(projectName || "Solar Project", 20, y + 10);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...DGRAY);
  doc.text(sysName, 20, y + 17);
  doc.setTextColor(...GRAY);
  doc.text(`${new Date().toLocaleDateString("en-GB")}`, 20, y + 22);
  y += 30;

  // ── Meta block ──
  const metaRows: [string, string][] = [
    ["System:",       sysName],
    ["Coordinates:",  location ? `${location.lat.toFixed(4)}° N  |  ${location.lon.toFixed(4)}° E` : "—"],
    ["PSH (irradiance):", location ? `${location.psh.toFixed(2)} kWh/m²/d` : "—"],
    ["DC Capacity:",  `${results.systemCapacitykW} kW  (${results.numberOfPanels} panels)`],
    ["Configuration:", `${results.panelsInSeries} in series  ×  ${results.panelsInParallel} branches`],
  ];
  y = metaBlock(doc, metaRows, y);
  y += 4;

  // ══ SECTION 1 ══
  if (y > 230) { addPage(); y = 30; }
  y = secHeader(doc, "1", t.secSpec, y);

  const specBody: [string, string, string][] = [];
  const sp = (p: string, v: string | number, u = "") => specBody.push([p, String(v), u]);

  sp("Peak Power (STC)",      results.peakPowerWp,        "Wp");
  sp("DC Capacity",           results.systemCapacitykW,   "kW");
  sp("Number of Panels",      results.numberOfPanels,     "");
  sp("Configuration",         `${results.panelsInSeries}S × ${results.panelsInParallel}P`, "");
  sp("Performance Ratio",     `${(PR * 100).toFixed(0)}`, "%");

  if (systemType === "on-grid") {
    sp("Grid-Tie Inverter",         `${results.inverterCapacitykW}`,           "kW");
    sp("Daily Production",          results.dailyProductionkWh,                "kWh/d");
    sp("Annual Production",         (results.dailyProductionkWh * 365).toFixed(0), "kWh/yr");
    sp("CO₂ Avoided / year",        ((results.dailyProductionkWh * 365) * 0.35).toFixed(0), "kg/yr");
    sp("DC Cable (Panel → Inverter)", results.cables.panelToInv,               "mm²");
    sp("AC Cable (Inverter → Grid)", results.cables.invToMain,                 "mm²");
  } else if (systemType === "off-grid" || systemType === "hybrid") {
    sp("Battery Bank (qty)",        `${results.totalBatteries}`,               "");
    sp("Battery Capacity",          results.batteryCapacityAh,                 "Ah");
    sp("Battery Voltage",           results.systemVoltage,                     "V");
    sp("Total Battery Energy",      ((results.batteryCapacityAh * results.systemVoltage) / 1000).toFixed(2), "kWh");
    sp("Inverter / Charger",        results.inverterCapacityW,                 "W");
    sp("MPPT Charge Controller",    results.mpptRatingA,                       "A");
    sp("DC Cable (Panel → MPPT)",   results.cables.panelToReg,                 "mm²");
    sp("DC Cable (MPPT → Battery)", results.cables.regToBatt,                  "mm²");
    sp("DC Cable (Battery → Inv.)", results.cables.battToInv,                  "mm²");
    sp("AC Cable (Inv. → Load)",    results.cables.invToLoad,                  "mm²");
    const annualEst = (results.systemCapacitykW || 0) * (location?.psh ?? 5) * 365 * PR;
    sp("Annual Production (est.)",  annualEst.toFixed(0),                      "kWh/yr");
    sp("CO₂ Avoided / year (est.)", (annualEst * 0.35).toFixed(0),             "kg/yr");
    // Wind turbine data
    if (systemType === "hybrid" && results.windConfig) {
      sp("── Wind Energy ──",        "",                                        "");
      sp("Wind Turbine Model",        results.windConfig.model,                  "");
      sp("Wind Turbines (qty)",       results.windConfig.count,                  "units");
      sp("Wind Power at Site",        results.windConfig.actualPowerW,           "W");
      sp("Wind Daily Energy",         results.windConfig.dailyKwh,               "kWh/d");
    }
    // Diesel generator data
    if (systemType === "hybrid" && results.dieselConfig) {
      sp("── Diesel Backup ──",       "",                                        "");
      sp("Diesel Generator Model",    results.dieselConfig.model,                "");
      sp("Diesel Generators (qty)",   results.dieselConfig.count,                "units");
      sp("Diesel Generator Power",    results.dieselConfig.powerKW,              "kW");
      sp("Diesel Hours / Day",        results.dieselConfig.hoursPerDay,          "h/d");
      sp("Diesel Fuel (daily)",       results.dieselConfig.dailyFuelL,           "L/d");
      sp("Diesel Daily Energy",       results.dieselConfig.dailyKwh,             "kWh/d");
    }
  } else if (systemType === "pumping") {
    sp("Pump Power",  results.pumpPowerHp, "HP");
    sp("Pump Power",  results.pumpPowerW,  "W");
  }

  autoTable(doc, {
    startY: y,
    head: [[t.paramCol, t.valueCol, t.unitCol]],
    body: specBody,
    theme: "grid",
    headStyles:      { fillColor: HEAD, textColor: WHITE, fontSize: 9, fontStyle: "bold" },
    bodyStyles:      { fontSize: 9, textColor: BLACK },
    alternateRowStyles: { fillColor: [248, 248, 248] },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 90 },
      1: { halign: "right", cellWidth: 50 },
      2: { halign: "left",  cellWidth: 42, textColor: GRAY },
    },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  // ══ SECTION 2 — COST ══
  if (costs) {
    if (y > 215) { addPage(); y = 30; }
    y = secHeader(doc, "2", `${t.secCost}  (reference prices — Algerian market)`, y);

    const costRows = [
      { n: `Solar Panels  (× ${results.numberOfPanels})`,       v: costs.panels },
      ...(costs.batteries > 0 ? [{ n: `Batteries  (× ${results.totalBatteries ?? 0})`, v: costs.batteries }] : []),
      { n: "Inverter / Charger",                                  v: costs.inverter },
      ...(costs.regulator > 0 ? [{ n: "MPPT Charge Controller",  v: costs.regulator }] : []),
      { n: "Cables, protection & miscellaneous",                  v: costs.cableAndMisc },
      { n: "Installation & labour",                               v: costs.installation },
    ].filter(r => r.v > 0);

    // Pie chart for cost breakdown
    const pieSlices = costRows.map((r, i) => ({
      label: r.n, value: r.v, color: PIE_COLORS[i % PIE_COLORS.length],
    }));
    const pieImg = makePieImage(pieSlices);
    if (y + 58 > 270) { addPage(); y = 30; }
    doc.addImage(pieImg, "PNG", 14, y, 182, 78);
    y += 82;

    autoTable(doc, {
      startY: y,
      head: [[t.costItem, t.amount, t.share]],
      body: costRows.map((r, i) => {
        const row = [r.n, fmt(r.v), `${((r.v / costs.total) * 100).toFixed(1)} %`];
        return row;
      }),
      foot: [[t.totalInvest, fmt(costs.total), "100 %"]],
      theme: "grid",
      headStyles:  { fillColor: HEAD, textColor: WHITE, fontSize: 9, fontStyle: "bold" },
      bodyStyles:  { fontSize: 9, textColor: BLACK },
      footStyles:  { fillColor: [220,220,220], textColor: BLACK, fontStyle: "bold", fontSize: 10 },
      alternateRowStyles: { fillColor: [248, 248, 248] },
      columnStyles: { 0: { fontStyle: "bold" }, 1: { halign: "right" }, 2: { halign: "right", cellWidth: 28 } },
      margin: { left: 14, right: 14 },
      didParseCell: (d: any) => {
        if (d.section === "body" && d.column.index === 0) {
          const idx = d.row.index;
          if (idx < PIE_COLORS.length) {
            const hex = PIE_COLORS[idx];
            const bigint = parseInt(hex.slice(1), 16);
            d.cell.styles.textColor = [(bigint >> 16) & 255, (bigint >> 8) & 255, bigint & 255];
          }
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 8;

    if (roi) {
      if (y > 240) { addPage(); y = 30; }
      autoTable(doc, {
        startY: y,
        head: [[t.secROI, ""]],
        body: [
          [t.annualSavings,  `${fmt(roi.annualSavings)} DZD / yr`],
          [t.payback,        roi.paybackYears <= 25 ? `${roi.paybackYears.toFixed(1)} years` : "> 25 years"],
          [t.netProfit,      `${roi.savingsOver25 >= 0 ? "+" : ""}${fmt(roi.savingsOver25)} DZD`],
          [t.roi25,          roi.savingsOver25 >= 0 ? `+${((roi.savingsOver25 / costs.total) * 100).toFixed(1)} %` : "Negative"],
          [t.tariff,         "5.00 DZD / kWh"],
        ],
        theme: "grid",
        headStyles: { fillColor: HEAD, textColor: WHITE, fontSize: 9, fontStyle: "bold", colSpan: 2 },
        bodyStyles: { fontSize: 9, textColor: BLACK },
        alternateRowStyles: { fillColor: [248, 248, 248] },
        columnStyles: { 0: { fontStyle: "bold", cellWidth: 110 }, 1: { halign: "right" } },
        margin: { left: 14, right: 14 },
      });
      y = (doc as any).lastAutoTable.finalY + 10;
    }
  }

  // ══ SECTION 3 — MONTHLY SOLAR ══
  if (monthly && monthly.length === 12) {
    if (y > 185) { addPage(); y = 30; }
    y = secHeader(doc, "3", `${t.secMonthly}  (NASA POWER — avg 2022/2023)`, y);

    const avgIrr  = monthly.reduce((s, m) => s + m.irr, 0) / 12;
    const avgTemp = monthly.reduce((s, m) => s + m.temp, 0) / 12;
    const cap     = results.systemCapacitykW || 1;

    // Bar chart for monthly GHI
    const barImg = makeBarImage(monthly.map(m => ({ label: m.label, value: m.irr })));
    if (y + 62 > 270) { addPage(); y = 30; }
    doc.addImage(barImg, "PNG", 14, y, 182, 65);
    y += 69;
    if (y > 185) { addPage(); y = 30; }

    autoTable(doc, {
      startY: y,
      head: [[t.monthCol, t.ghiCol, t.tempCol, `${t.yieldCol}  [${cap} kW]`, t.shareCol, t.classCol]],
      body: monthly.map((m, i) => [
        mon[i],
        m.irr.toFixed(3),
        m.temp.toFixed(1),
        (m.irr * cap * PR * 30).toFixed(0),
        ((m.irr / (avgIrr * 12)) * 100).toFixed(1) + " %",
        classify(m.irr),
      ]),
      foot: [[
        t.annAvg,
        avgIrr.toFixed(3),
        avgTemp.toFixed(1),
        (avgIrr * cap * PR * 365).toFixed(0) + " kWh/yr",
        "100 %",
        "—",
      ]],
      theme: "grid",
      headStyles:  { fillColor: HEAD, textColor: WHITE, fontSize: 8.5, fontStyle: "bold" },
      bodyStyles:  { fontSize: 8.5, textColor: BLACK },
      footStyles:  { fillColor: [220,220,220], textColor: BLACK, fontStyle: "bold", fontSize: 8.5 },
      alternateRowStyles: { fillColor: [248, 248, 248] },
      columnStyles: { 0: { fontStyle: "bold", cellWidth: 28 }, 1: { halign: "right" }, 2: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "right" }, 5: { halign: "center" } },
      margin: { left: 14, right: 14 },
      didParseCell: (d: any) => {
        if (d.section === "body" && d.column.index === 5) {
          const v = (d.cell.raw as string).toLowerCase();
          if (v === "excellent")    d.cell.styles.textColor = [22, 163, 74];
          else if (v === "very good") d.cell.styles.textColor = [16, 185, 129];
          else if (v === "moderate") d.cell.styles.textColor = [220, 80, 60];
        }
      },
    });
    y = (doc as any).lastAutoTable.finalY + 8;

    // Seasonal
    const seasons = [
      ["Winter (Dec-Feb)", [11,0,1]],
      ["Spring (Mar-May)", [2,3,4]],
      ["Summer (Jun-Aug)", [5,6,7]],
      ["Autumn (Sep-Nov)", [8,9,10]],
    ];
    if (y + 30 < 270) {
      autoTable(doc, {
        startY: y,
        head: [[t.season, t.avgGhi, t.annGhi, t.avgTemp, t.classif]],
        body: seasons.map(([name, idx]) => {
          const mths = idx as number[];
          const ghi  = mths.reduce((a, i) => a + monthly[i].irr, 0) / 3;
          const temp = mths.reduce((a, i) => a + monthly[i].temp, 0) / 3;
          return [name as string, ghi.toFixed(2), (ghi * 91.25).toFixed(0), temp.toFixed(1), classify(ghi)];
        }),
        theme: "grid",
        headStyles:  { fillColor: HEAD, textColor: WHITE, fontSize: 8.5, fontStyle: "bold" },
        bodyStyles:  { fontSize: 8.5, textColor: BLACK },
        alternateRowStyles: { fillColor: [248, 248, 248] },
        columnStyles: { 0: { fontStyle: "bold" }, 1: { halign: "right" }, 2: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "center" } },
        margin: { left: 14, right: 14 },
      });
      y = (doc as any).lastAutoTable.finalY + 8;
    }
  }

  // ══ SECTION 4 — PANEL SPACING ══
  if (spacing) {
    if (y > 210) { addPage(); y = 30; }
    y = secHeader(doc, "4", t.secSpacing, y);

    autoTable(doc, {
      startY: y,
      head: [[t.paramCol, t.valueCol, t.unitCol]],
      body: [
        [t.panelLen,    spacing.L.toFixed(2),                     "m"],
        [t.tiltAngle,   `${spacing.tilt}`,                        "°"],
        [t.latitude,    `${spacing.lat.toFixed(2)}`,              "°N"],
        [t.rowSpacing,  spacing.d.toFixed(2),                     "m"],
        [t.dMin,        spacing.dMin.toFixed(2),                  "m"],
        [t.winterElev,  spacing.solarElevWinter.toFixed(1),       "°"],
        [t.summerElev,  spacing.solarElevSummer.toFixed(1),       "°"],
        [t.winShadow,   spacing.shadowLengthWinter.toFixed(2),    "m"],
        [t.sumShadow,   spacing.shadowLengthSummer.toFixed(2),    "m"],
        [t.gcr,         `${(spacing.gcr * 100).toFixed(1)}`,      "%"],
        [t.shadedFrac,  `${(spacing.shadedFraction * 100).toFixed(1)}`, "%"],
        [t.annualLoss,  `${spacing.annualLoss.toFixed(1)}`,       "%"],
        [t.status,      spacing.d >= spacing.dMin ? "OK — No shading" : "WARNING — Shading possible", ""],
      ],
      theme: "grid",
      headStyles:  { fillColor: HEAD, textColor: WHITE, fontSize: 9, fontStyle: "bold" },
      bodyStyles:  { fontSize: 9, textColor: BLACK },
      alternateRowStyles: { fillColor: [248, 248, 248] },
      columnStyles: { 0: { fontStyle: "bold", cellWidth: 90 }, 1: { halign: "right", cellWidth: 50 }, 2: { textColor: GRAY, cellWidth: 42 } },
      margin: { left: 14, right: 14 },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // ── Footers ──
  const nPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= nPages; i++) { doc.setPage(i); docFooter(doc, i, nPages, t.footer); }

  const safe = (projectName || "project").replace(/[^a-z0-9]/gi, "_").toLowerCase();
  doc.save(`LuminaSizer_${safe}_report.pdf`);
}

// ─── LOCATION RESOURCE PDF ────────────────────────────────────────────────────
export interface LocationPdfOptions {
  monthly: { label: string; irr: number; temp: number }[];
  lat: number;
  lon: number;
  locationName?: string;
  lang?: "en" | "fr" | "ar";
}

export function generateLocationPdf(opts: LocationPdfOptions) {
  const { monthly, lat, lon, locationName } = opts;
  const t   = T;
  const mon = MONTH_NAMES;
  const PR  = 0.82;

  const avgIrr  = monthly.reduce((s, m) => s + m.irr, 0) / 12;
  const avgTemp = monthly.reduce((s, m) => s + m.temp, 0) / 12;
  const peakM   = monthly.reduce((a, b) => a.irr > b.irr ? a : b);
  const lowM    = monthly.reduce((a, b) => a.irr < b.irr ? a : b);
  const peakIdx = monthly.indexOf(peakM);
  const lowIdx  = monthly.indexOf(lowM);

  const optTilt    = Math.round(Math.abs(lat));
  const winterTilt = Math.min(60, Math.round(Math.abs(lat)) + 15);
  const summerTilt = Math.max(10, Math.round(Math.abs(lat)) - 15);

  const climateZone =
    lat > 33 ? "North Algeria — Mediterranean / Semi-Arid" :
    lat > 25 ? "Central Algeria — Arid / Pre-Saharan" :
               "Deep Sahara — Hyper-Arid";

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  let y = 0;

  docHeader(doc, `${t.subtitle}  —  Solar Site Resources`);
  y = 30;

  doc.setFillColor(...LGRAY);
  doc.rect(14, y, 182, 28, "F");
  doc.setFontSize(15);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...BLACK);
  doc.text(locationName ? `Solar Report — ${locationName}` : "Solar Site Resource Report", 20, y + 10);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...DGRAY);
  doc.text(`Coordinates: ${lat.toFixed(5)}° N,  ${lon.toFixed(5)}° E`, 20, y + 17);
  doc.setTextColor(...GRAY);
  doc.text(`Source: NASA POWER (ALLSKY_SFC_SW_DWN + T2M_MAX)  —  avg 2022-2023  —  ${new Date().toLocaleDateString("en-GB")}`, 20, y + 23);
  y += 34;

  const rows: [string, string][] = [
    ["Location:",           locationName || "Custom coordinates"],
    ["Coordinates:",        `${lat.toFixed(5)}° N  /  ${lon.toFixed(5)}° E`],
    ["Climate Zone:",       climateZone],
    ["Annual GHI:",         `${(avgIrr * 365).toFixed(0)} kWh/m²/yr  (avg: ${avgIrr.toFixed(2)} kWh/m²/d)`],
    ["Avg Max Temp:",       `${avgTemp.toFixed(1)} °C`],
    ["Best Month:",         `${mon[peakIdx]}  —  ${peakM.irr.toFixed(2)} kWh/m²/d`],
    ["Lowest Month:",       `${mon[lowIdx]}  —  ${lowM.irr.toFixed(2)} kWh/m²/d`],
    ["Classification:",     classify(avgIrr)],
    ["Yield / kWp (est.):", `${(avgIrr * 365 * PR).toFixed(0)} kWh/yr  (PR = ${PR})`],
    ["CO₂ avoided / kWp:", `${(avgIrr * 365 * PR * 0.35).toFixed(0)} kg CO₂/yr`],
  ];
  y = metaBlock(doc, rows, y);
  y += 4;

  // Section 1: Monthly table
  if (y > 190) { doc.addPage(); docHeader(doc, t.subtitle); y = 30; }
  y = secHeader(doc, "1", t.secMonthly, y);

  // Bar chart for monthly GHI
  const locBarImg = makeBarImage(monthly.map(m => ({ label: m.label, value: m.irr })));
  if (y + 62 > 270) { doc.addPage(); docHeader(doc, t.subtitle); y = 30; }
  doc.addImage(locBarImg, "PNG", 14, y, 182, 65);
  y += 69;
  if (y > 190) { doc.addPage(); docHeader(doc, t.subtitle); y = 30; }

  autoTable(doc, {
    startY: y,
    head: [[t.monthCol, t.ghiCol, t.tempCol, "1 kWp Yield (kWh/mo)", "Annual Share (%)", t.classCol]],
    body: monthly.map((m, i) => [
      mon[i],
      m.irr.toFixed(3),
      m.temp.toFixed(1),
      (m.irr * PR * 30).toFixed(1),
      ((m.irr / (avgIrr * 12)) * 100).toFixed(1) + " %",
      classify(m.irr),
    ]),
    foot: [[t.annAvg, avgIrr.toFixed(3), avgTemp.toFixed(1), (avgIrr * PR * 365).toFixed(0), "100 %", classify(avgIrr)]],
    theme: "grid",
    headStyles:  { fillColor: HEAD, textColor: WHITE, fontSize: 8.5, fontStyle: "bold" },
    bodyStyles:  { fontSize: 8.5, textColor: BLACK },
    footStyles:  { fillColor: [220,220,220], textColor: BLACK, fontStyle: "bold", fontSize: 8.5 },
    alternateRowStyles: { fillColor: [248, 248, 248] },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 28 }, 1: { halign: "right" }, 2: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "right" }, 5: { halign: "center" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  // Section 2: Seasonal
  if (y > 230) { doc.addPage(); docHeader(doc, t.subtitle); y = 30; }
  y = secHeader(doc, "2", t.secSeason, y);

  const seasons = [
    ["Winter  (Dec - Feb)", [11,0,1]],
    ["Spring  (Mar - May)", [2,3,4]],
    ["Summer  (Jun - Aug)", [5,6,7]],
    ["Autumn  (Sep - Nov)", [8,9,10]],
  ];
  autoTable(doc, {
    startY: y,
    head: [[t.season, t.avgGhi, t.annGhi, t.avgTemp, t.classif]],
    body: seasons.map(([name, mths]) => {
      const ghi  = (mths as number[]).reduce((a, i) => a + monthly[i].irr, 0) / 3;
      const temp = (mths as number[]).reduce((a, i) => a + monthly[i].temp, 0) / 3;
      return [name, ghi.toFixed(2), (ghi * 91.25).toFixed(0), temp.toFixed(1), classify(ghi)];
    }),
    theme: "grid",
    headStyles:  { fillColor: HEAD, textColor: WHITE, fontSize: 8.5, fontStyle: "bold" },
    bodyStyles:  { fontSize: 8.5, textColor: BLACK },
    alternateRowStyles: { fillColor: [248, 248, 248] },
    columnStyles: { 0: { fontStyle: "bold" }, 1: { halign: "right" }, 2: { halign: "right" }, 3: { halign: "right" }, 4: { halign: "center" } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  // Section 3: Recommendations
  if (y > 230) { doc.addPage(); docHeader(doc, t.subtitle); y = 30; }
  y = secHeader(doc, "3", t.secInstall, y);

  autoTable(doc, {
    startY: y,
    head: [[t.paramCol, t.recValue, t.notes]],
    body: [
      [t.tiltAnn,   `${optTilt}°`,    "Maximises annual production"],
      [t.tiltWin,   `${winterTilt}°`, "Optimal performance Dec-Feb"],
      [t.tiltSum,   `${summerTilt}°`, "Optimal performance Jun-Aug"],
      [t.azimuth,   "180° (True South)", "Northern hemisphere"],
      [t.pr,        `${PR} (${(PR*100).toFixed(0)} %)`, "Cable, temperature & soiling losses included"],
      [t.yieldKwp,  `${(avgIrr * 365 * PR).toFixed(0)} kWh`, `Avg GHI ${avgIrr.toFixed(2)} kWh/m²/d`],
      [t.co2,       `${(avgIrr * 365 * PR * 0.35).toFixed(0)} kg/yr`, "vs diesel generator"],
      [t.solar,     avgIrr >= 6 ? "Very High (>80%)" : avgIrr >= 5 ? "High (65-80%)" : "Moderate (50-65%)", ""],
    ],
    theme: "grid",
    headStyles:  { fillColor: HEAD, textColor: WHITE, fontSize: 8.5, fontStyle: "bold" },
    bodyStyles:  { fontSize: 8.5, textColor: BLACK },
    alternateRowStyles: { fillColor: [248, 248, 248] },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 70 }, 1: { halign: "right", cellWidth: 55 }, 2: { textColor: GRAY } },
    margin: { left: 14, right: 14 },
  });
  y = (doc as any).lastAutoTable.finalY + 8;

  const nPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= nPages; i++) { doc.setPage(i); docFooter(doc, i, nPages, t.footer); }

  const locSafe = (locationName || `${lat.toFixed(2)}N_${lon.toFixed(2)}E`).replace(/[^a-z0-9]/gi, "_");
  doc.save(`LuminaSizer_SolarResource_${locSafe}.pdf`);
}
